### PR TITLE
Adding the modificaiton reification and baseline

### PR DESCRIPTION
**Pull request by StevenCostiou**
If accepted, add the following in a readme: 

Metacello new
    baseline: 'ChangeDetector';
    repository: 'github://MarcusDenker/ChangeDetector';
    load.

Still problem with race conditions? It can be seen on the tests, they don't pass if all are executed throug using the button near the class name, but they all go green individually.

### CODE REVIEW

**Comment by MarcusDenker** [comment]
for the tests: I think the problem is that the test runner has an exception handler for "Error". But the modification exception is a subclass of error, too.

I was wondering if we could not change the superclass of the exception ModificationForbidden to Exception?

**Comment by StevenCostiou** [comment]
Ah, yes, changing the subclass to Exception works better.
One of test is yellow but I don't think there is any relation. I will commit in a few minutes.

**Comment by StevenCostiou** [comment]
Ok I fixed a bug in the stopNotify logic.
However the ModificationForbidden is not part of the commit, it is in Pharo. Else I would have to move it to the ChangeDetector package until modified in Pharo?

**Comment by MarcusDenker** [comment]
we could add it to this repo for now. I would like to change it in Pharo, though

**Pull request merged**
